# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 870f5bd78749cd3dffa93323823dba4bfa26b7f2ca0c7ddf7e12bc8a33e41342ca2daa04e4744ad0d868097c2b742adde9db43d3cd4435c7c1339b511761b32e

test:
  secret_key_base: 5e0c074ac154aeede6e99107347166a8201b2c811423e5219d638c75a27c1565a55f987999ace489ed2d7f6360ff2a1a399fa9df2c718b78c28b62703a1b6cc3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
